# Generated by Django 4.2.4 on 2023-09-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='FullName')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True, verbose_name='Slug')),
                ('bio', models.TextField(verbose_name='Bio')),
                ('image', models.FileField(upload_to='uploads/authors/images/', verbose_name='image')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='DateOfBirth')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='DateOfDeath')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('icon', models.FileField(upload_to='uploads/category/icons/', verbose_name='Icon')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=False, verbose_name='IsActive')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Catagories',
            },
        ),
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('pages', models.IntegerField(verbose_name='NumberOfPages')),
                ('price', models.FloatField(verbose_name='Price')),
                ('cover', models.ImageField(upload_to='uploads/ebooks/covers/', verbose_name='Cover')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('ebook', models.FileField(upload_to='uploads/ebooks/files/', verbose_name='EBook')),
                ('is_active', models.BooleanField(default=False, verbose_name='IsActive')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(related_name='books', to='books.author', verbose_name='Authors')),
                ('category', models.ManyToManyField(related_name='books', to='books.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'EBook',
                'verbose_name_plural': 'EBooks',
            },
        ),
    ]
