# Generated by Django 4.2.4 on 2023-09-26 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='authors/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='category/icons/', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='cover',
            field=models.ImageField(upload_to='ebooks/covers/', verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='ebook',
            field=models.FileField(upload_to='ebooks/files/', verbose_name='EBook'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='pages',
            field=models.IntegerField(blank=True, null=True, verbose_name='NumberOfPages'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Body')),
                ('is_active', models.BooleanField(default=False, verbose_name='IsActive')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='books.ebook')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
